// Code generated by "stringer -type=BACnetComfirmedServiceChoice -linecomment"; DO NOT EDIT.

package generate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServiceConfirmedAcknowledgeAlarm-0]
	_ = x[ServiceConfirmedComfirmedCOVNotification-1]
	_ = x[ServiceConfirmedComfirmedEventNotification-2]
}

const _BACnetComfirmedServiceChoice_name = "确认报警服务证实COV通告服务证实事件通过服务"

var _BACnetComfirmedServiceChoice_index = [...]uint8{0, 18, 39, 63}

func (i BACnetComfirmedServiceChoice) String() string {
	if i >= BACnetComfirmedServiceChoice(len(_BACnetComfirmedServiceChoice_index)-1) {
		return "BACnetComfirmedServiceChoice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BACnetComfirmedServiceChoice_name[_BACnetComfirmedServiceChoice_index[i]:_BACnetComfirmedServiceChoice_index[i+1]]
}
